Remove dependencies to template-library
Pelagicore/template-service-wizard pull request #1
Opened 2017-11-23 14:44 UTC by DunderRoffe

As it is not possible to simply pull template-service and use it without also having to run intricate renaming scripts. I think it is better to keep the template-service and the template generated by this wizard as two different (although very similar) things.

This also allows us to have more wizard specifics etc..

Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>

2017-11-23 15:11 UTC, caybro requested changes
I'd prefer if the stuff got commented out instead of removed, with a nice remark + URL pointing to the template-library repo. wdyt?

2017-11-23 15:47 UTC, breakreturn commented
In the example of template-service being dependent on template-library I think we had it as an example while avoiding deps by using commented-out code I believe.

2017-11-24 09:34 UTC, GordanM commented
@DunderRoffe if you like at the upstream template there is a nice soultion using package config. Maybe you can copy just the whole template for now? (https://github.com/Pelagicore/template-service/blob/master/CMakeLists.txt).

2017-11-27 08:17 UTC, DunderRoffe commented
@GordanM 
As I see it the benefit of having the library dependency in the code generated by the wizard is to quickly be able to add a dependency to the build (likely not the template-library). Most dependencies wont be optional. Hence in most cases, there wont be a need for the package config.

2017-11-27 08:17 UTC, DunderRoffe commented
@caybro updated :)

2017-11-27 08:20 UTC, GordanM commented
@DunderRoffe the dependencies are stated through the package config, so I am not sure why would you remove it? But I get your point that there is a need to have a boiler plate way to state dependencies (either optional or not). For me both ways are OK, either optional dependencies or commented out code.

2017-12-05 15:29 UTC, merged